config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'movie#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  # get 'register', to: 'users#new'
  delete 'logout', to: 'sessions#destroy'
  get 'share', to: 'movie#new'
  post 'share', to: 'movie#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :user_movies
  has_many :users, through: :user_movies
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, length: { minimum: 3, maximum: 20, allow_blank: true},
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 3, maximum: 20, allow_blank: true }

  has_many :user_movies
  has_many :movies, through: :user_movies
end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  before_action :require_user, only: [:create, :new]
  def index
    # @user = current_user
    @movie = Movie.all
  end

  def new

  end

  def create
    if params[:movie][:url].blank?
      flash.now[:error] = 'Please enter url'
      render 'new'
    else
      movie = Movie.find_or_create_by!(url: movie_params[:url])
      current_user.user_movies.find_or_create_by(movie_id: movie.id)
      redirect_to root_path
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: user_params[:username])
    if @user.nil?
      create_user
    else
      login(@user)
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to login_path
  end

  private

  def login(user)
    if user&.authenticate(user_params[:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:error] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def create_user
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      login(@user)
    else
      render :new
    end
  end

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in'
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def new
  #   @user = User.new
  # end
  #
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to root_path
  #   else
  #     render "new"
  #   end
  # end
  #
  # private
  #
  # def user_params
  #   params.require(:user).permit(:username, :password)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}", class: 'iframe')
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%#= link_to "Chatroom", root_path,  class: "item" %>
<div class="left menu" id="logo">
  <div class="ui grid">
    <i class="orange film icon" ></i>
    <%= link_to "Funny Movies", root_path, class: "ui green big" %>
  </div>
</div>
<div class="right menu">
  <div class="ui item">
    <% if logged_in? %>
      <div class="item">
        <p>Welcome <%= current_user.username %></p>
      </div>
      <div class="item">
        <%= link_to "Share a movie", share_path, class: "ui primary button" %>
      </div>
      <div class="item">
        <%= link_to "Log out", logout_path, method: :delete,  class: "ui primary button" %>
      </div>
    <% else %>
      <%= link_to "Login/Register", login_path, class: "ui primary button" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funny Movies</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movie/index.html.erb
</br>
<div class="ui placeholder segment">
  <% @movie.each do |movie| %>
    <div class="ui two column very relaxed stackable grid">
      <div class="column">
        <%= embed(movie.url) %>
      </div>
      <div class="middle aligned column">
        <h1>Movie Title</h1>
        <h2>Share by: <%= movie.users.pluck(:username).join(', ') %></h2>
        <p>Description:</p>
        <p>Cốt truyện Spider-Man: No Way Home xoay quanh cuộc sống đã bị đảo lộn của Peter Parker
          (Tom Holland) bởi kẻ phản diện Mysterio trong Spider-Man: Far From Home đã công bố danh tính thật
          của cậu chàng là Spider-Man cho cả thế giới biết. Để bảo vệ gia đình và bạn bè của mình,
          Peter yêu cầu sự giúp đỡ của phù thủy toàn năng Doctor Strange (Benedict Cumberbatch)
          nhằm khiến mọi người quên đi danh tính của mình. Nhưng một trục trặc đã xảy ra và năm
          kẻ thù cũ của Spider- Man đến từ các vũ trụ khác bước vào cuộc đời của anh bao gồm:
          Doc Ock (Alfred Molina), Green Goblin (Willem Dafoe), Electro (Jamie Foxx),
          Sandman (Thomas Haden Church) và The Lizard  (Rhys Ifans). Nghe thật hấp dẫn phải không nào? </p>
      </div>
      <div class="ui vertical">

      </div>
    </div>
  <% end %>
</div>

app/views/movie/new.html.erb
<h2 class="ui center aligned large header">
  Share a Youtube Movie
</h2>

<div class="ui placeholder segment">
  <div class="ui very relaxed stackable grid">
    <div class="column">
      <%= form_for(:movie, html: {class: "ui form", role: "form"}, url: share_path) do |f| %>
        <%= f.label :url, "Youtube URL:" %>
        <div class="ui left icon input" id="url_share">
          <%= f.text_field :url, placeholder: ""%>
        </div>
        <%= f.button "Share", class: "ui orange submit button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.key?(field) %>
  <%= obj.errors.full_messages_for(field).join(', ') %>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded") do |form| %>
    <div class="row justify-content-center">
      <div class= "col-10">
        <div class="form-group row">
          <%= form.label :username, style: "display: block", class: "col-2 col-form-label"%>
          <div class="col-10">
            <%= form.text_field :username, class: "form-control"%>
          </div>
        </div>
        <br>
        <div class="form-group row justify-content-center">
          <%= form.label :email, style: "display: block", class: "col-2 col-form-label"%>
          <div class="col-10">
            <%= form.email_field :email, class: "form-control shadow rounded"%>
          </div>
        </div>
        <br>
        <div class="form-group row justify-content-center">
          <%= form.label :password, style: "display: block", class: "col-2 col-form-label"%>
          <div class="col-10">
            <%= form.password_field :password, class: "form-control shadow rounded"%>
          </div>
        </div>
        <br>
        <div class="form-group row justify-content-center">
          <%= form.submit(@user.new_record? ? "Sign up" : "Update account", class:" btn btn-success") %>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to "Back to articles", articles_path, class:"row justify-content-center"%>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> Sign up</h1>

<%= render "form", user: @user %>

<br>